### ISSUE TITLE
structure of `course-website` yml content in `_quarto.yml`

### ISSUE THREAD

**Issue by paciorek** [qmd-lab/course-website#12]
We discussed having `weeks` and `days` keys as a two-level time hierarchy.

I'm wondering if `units` and `sessions` would be more general without being too generic. Weeks/days definitely maps onto how you structure Stat 20 and how things are structured in various DS course websites, but one could imagine one that is not so calendar-tied.  Not sure if that naming would feel unnatural for Stat 20 since I know you have a small number of units that are distinct from weeks.

**Comment by andrewpbray** [comment]
Hmm. I like those names, though you're right about "unit" - that has a specific meaning to many courses that doesn't map to weeks neccessarily.

What about differentating between "groups" and their "items"?

Here's what it looks like now:

```
  schedule:
    - week: 1
      days:
        - topic: "Random Variables"
          display-date: Jan 16
          date: 1/16/24
          unit: Probability
          items:
          - type: Notes
            href: 1-probability/1-random-variables/notes.qmd
          - type: Slides
            href: 1-probability/1-random-variables/slides.qmd
```
That would become:
```
schedule:
  group-label: weeks
  items:
    - item-label: 1
       group-label: days
       items:
        - item-label: "Random Variables"
          display-date: Jan 16
          date: 1/16/24
          unit: Probability
          group-label: materials
          items:
          - type: Notes
            href: 1-probability/1-random-variables/notes.qmd
          - type: Slides
            href: 1-probability/1-random-variables/slides.qmd
```
Ugh, that's not pretty.

Here's another approach: instead of requiring a certain structure for the entire tree, just reserve the key that holds the info that is modified: in this case `items`. Then instead of iterating over that certain structure, you build up a list of `items` where ever they lay, then iterate through that list. I'm not actually sure how to code this up in typescript, but seems conceptually possible.

The extension could hold a few ejs templates in addition to the default and the documentation could show how to set up a `schedule` that works for that template. As long as the reserved key is used only for those items, it should be able to permit a wide range of schedules.
