### ISSUE TITLE
where should schedule content be

### ISSUE THREAD

**Issue by paciorek** [qmd-lab/course-website#3]
Minor thing, but having the actual schedule content in `_config.yml` rather than, say, `schedule-full.yml` feels a bit confusing to me. I think having the name of the input file and the generated filename of `schedule.yml` be more similar is more intuitive.

I may well just be not seeing the good reasons to have it in `_config.yml`.

**Comment by andrewpbray** [comment]
This sort of feedback is very helpful. There are few options here that I've kicked around and actually many more options open up now that this is being structured as a Quarto extension. They include:

1. Storing all options (schedule, partial-render, etc) in a separate file, which could be called `config.yml` or `schedule_full.yml` or `cw_config.yml` or similar.
2. Storing all options (essentially all of the current contents of config.yml) as meta-data in `quarto.yml`.
3. Some combo of the two, maybe where schedule is an external file but other options are in _quarto.yml.

The idea with a project extension is that just in the same way you can make a custom format extension with its own options, allowing your user to somethign like this:

```
format:
  andrewshtml:
    newfeature1: "blue"
    newfeature2: true
```

You can have a user of a custom project do something like (in `_quarto.yml`):

```
project:
  type:
    course-website:
      schedule: <all the schedule stuff>
      partial-render: <options>
```

Or alternatively

```
project:
  type: course-website

course-website:
  schedule: <all the schedule stuff>
  partial-render: <options>
```

Or where that `schedule` key could (optionally?) link off to a `schedule.yml`.

And the wonderful think about packaging this up as an extension is that anyone can get access to this funtionality by going to a (pre-existing) quarto website dir and do:

```
quarto add qmd-lab/quarto-course-website
```

So we can separate the extension functionality from particular website templates. Among other things, it allows us to update the functionality without needing to worry how a particular existing website is structured.

```
quarto update extension qmd-lab/quarto-course-webiste
```

Charles and I are very close to debugging some stuff on the `use-v-1-5` branch, then I'd love to brainstorm with you what would feel most natural from a user prospective.
